# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7fe00e04731a3cf16aefe71f5a3d3a60efa67612743755b7ee75ebbeeafd2d922c8c5663043f3ac9ff68f0d16473e4b2e65e487952454bf8eeb3563e5048ae

test:
  secret_key_base: 31b0c5618e6dec1c7ac9e7a4d72f209174100a5107211ff5169985227d7ec58ecc4cc2d6bcd5eea13e3a7a2ebb87e10514da6cf56344af9fa54e2a4ea473645c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
